### ISSUE TITLE
Cannot specify an USB device and a Master device

### ISSUE THREAD

**Issue by Porrumentzio** [ovenwerks/studio-controls#27]
When I connect a USB device JACK is automatically stopped by SC. So I have to manually select `USB,0,0`. Then, Master device becomes `USB JACK MASTER` and I can not get back to `Generic,0,0` until I disconnect the USB device.

I suppose that this is not the expected behaviour and that it is to have a Master (internal sound card) and a USB.
___
When I have not the USB connected, I can't select any on USB Device. I don't know if SC should save the identifier for the card, so that when it's connected it will recognize it automatically.

**Comment by Porrumentzio** [comment]
![studio-controls-USB-Master](https://user-images.githubusercontent.com/61913683/99559504-28847e80-29c5-11eb-9fa8-4f5391dc9bcf.gif)

**Comment by eeickmeyer** [comment]
This is actually by design. USB devices are listed separately and take-over when set as "USB device that should be Master". Once JACK is started, it treats the USB device as master. JACK, by default, will not treat any device as master unless it's USB, studio-controls gets around this by using zita-ajbridge to make the USB devices the master device.

Notice how it says "(no USB)" in the JACK Master Device selection. This is because USB devices *cannot* be selected as master, but the next menu does that for you.
