### ISSUE TITLE
Dummy backend config still takes over ALSA devices on start

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#28]
Setting JACK backend to dummy in Cadence and starting doesn't stop PulseAudio using the output device, but if I set studio-controls to dummy and start JACK, the output device is still taken over.

**Comment by ovenwerks** [comment]
So long as pulse is bridged to jack, pulse should not see any audio devices. The pulse->jack bridge is not properly made and will cause xruns if pulse can see another device. This will be fixed with pipewire I would guess , as there is zero possibility that the pulse->jack bridge will see any work before pipewire is the standard desktop audio server.
