### ISSUE TITLE
Add Extra sends parameters which don't work

### ISSUE THREAD

**Issue by KeithSBB** [ovenwerks/studio-controls#41]
If I use the current Fedora 33 Jam version of studio controls to add my internal PCH sound device and an extra device I see it in the Carla patch bay, and can route signals to it, but no sound comes out.  The AutoJack log shows:
2020-12-24 11:51:09,038 - root - DEBUG - device bridging comand line: /usr/bin/zita-j2a -j PCH,1,0-out -d hw:PCH,1,0 -r 48000 -p 128 -n 3 -c 100

If I Change this command to: 
/usr/bin/zita-j2a -j PCH,1,0-out -d hw:1,0 -r 48000 -p 128 -n 3 -c 100
and run it from a console window, I then see the bridge port, can route to it and I get sound out.

The difference is the  -d parameter where AutoJack has -d hw:PCH,1,0 versus  -d hw:1,0
There are no other extra devices to chose from in the Studio-controls Add drop down.

**Comment by ovenwerks** [comment]
PCH,1,0 is not the same device as 1,0. So if hw:1,0 works and you get sound where you want it... I would guess hw:1,0 is the same as hw:PCH,0,0.
Now if PCH,0,0 does not show in the drop down, it could be because PHC,0,0 is already selected as JACK master but you are using a USB device as JACK master as well.
If this is the case: A) The latest version of studio-controls has already fixed this
B) in your case you can:

> set USB master to "No USB Master"
> Change the JACK Master to PCH,1,0 (we know you have that)
> Apply (audio will vanish)
> Set USB Master back to your USB device.
> Apply (sound will go back to USB)
>PCH,0,0 should now show up in extra devices

You can see why this was changed in later versions. studio-controls 2.1.0 when it is packaged should be a nicer experience.
Also let me know if this solves your problem.

**Comment by ovenwerks** [comment]
Assuming this has been resolved

**Comment by KeithSBB** [comment]
Hi Len,I have not installed your latest build and I still use the version that came with Fedora jam 33.  I also assume the problem was fixed.  I want to wait for the next release of Fedora Jam since it will be using pipewire.Thanks for everything you do.On Feb 26, 2021 10:21 AM, Len <notifications@github.com> wrote:
Assuming this has been resolved
