### ISSUE TITLE
No sound with other user after close session

### ISSUE THREAD

**Issue by rlorite** [ovenwerks/studio-controls#42]
If I start Jack from studio-controls and click the "apply audio settings" button then, when I log out and open the session of another system user (who does not use Jack), this user has no sound until she restarts the system.

If I don't click the "apply audio settings" button there is no problem.

I am using Kubuntu 20.10 with Ubuntu Studio PPA Backport

**Comment by ovenwerks** [comment]
Yup, this is a problem with systemd and whichever desktop environment you use. They all do the same thing. when asked to reboot they send a systemd message via dbus... except for a logout where the session logind started is left running and a second logind session is started. The DE needs to send a user dbus message to the user sytemd set of units to start the systemd-exit.service.
This is not just the DE you happen to be using but seems to be all of them.

This is a DE problem, not a studio-controls problem, we can't fix it here.

**Comment by rlorite** [comment]
Thank you very much for your response.

Is there a workaround to "fix" it, maybe restart some service at the beginning of that session?

**Comment by ovenwerks** [comment]
If your DE has a way of running a script on logout, a script with:
systemctl --user start systemd-exit.service
Would do. Otherwise running a utility that the DE shuts down on logout and catching the kill signal may be another option but be warned this is likely to result in one being logged out rather than shutting down or rebooting when these are attempted.
