### ISSUE TITLE
AttributeError: Handler button_cb not found

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#5]
The GUI opens, but the terminal shows an issue;

```
± studio-controls

jack message received: jack server is not running or cannot be started
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 105, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 85, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler button_cb not found

...
```

**Comment by ovenwerks** [comment]
Yes :) WIP

**Comment by Marzal** [comment]
Similar problem with [gnome-gmail](https://github.com/davesteele/gnome-gmail/issues/31) was fixed [this](https://github.com/davesteele/gnome-gmail/commit/2f07a2d1f8e7d3fc14a1fd44681612ef9c3491d5) way. In case this info helps.
https://github.com/ovenwerks/studio-controls/blob/9e9111bdf840a5249d4bb1943ebf83f5fd7302d3/usr/bin/studio-controls#L161

This is all I could find about this error "_extract_handler_and_args", I'm no python developer

http://www.peteronion.org.uk/PyGobjectGtk+3/PyGtk.html
"These error messages are produced because there are handlers specified in the glade file that have not yet been implemented in the Handlers class."

button_cb handler in the [glade file](https://github.com/ovenwerks/studio-controls/blob/9e9111bdf840a5249d4bb1943ebf83f5fd7302d3/usr/share/studio-controls/studio-controls.glade#L1211) is not defined in [studio-controls](https://github.com/ovenwerks/studio-controls/blob/9e9111bdf840a5249d4bb1943ebf83f5fd7302d3/usr/bin/studio-controls#L396)

I think this is also related with #8

**Comment by ovenwerks** [comment]
This should be fixed (is here) with latest commit.
