### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by iso-l588** [ovenwerks/studio-controls#55]
On my setup, over some time I use several different USB interfaces.

Since Studio Controls came along I don't really see any reason to continue using QjackCtr, but is has one feature I'd like to see in Studio Controls as well: naming interfaces. QjackCtrl makes this possible while Studio Controls seem to just list generic names, USB1, USB2, etc.

Otherwise, thanks a lot for maintaining and making Ubuntu Studio better and better!

**Comment by ovenwerks** [comment]
Studio-controls does already allow naming interfaces. Any added (extra) device can have that device's JACK client name set in the extra devices tab. This was added in version 2.1.60 beta (we are now up to 2.1.67 with bug fixes). However, I am not sure this is what you mean because you say "QjackCtrl makes this possible". Qjackctl actually allows renaming of _ports_ rather than the client itself and I have found that the port rename in Qjackctl does not show up in other applications always. The next release will be 2.2.0 which should be basically the same as 2.1.67 (I hope :)  )  So if you wish to try 2.1.67 and see if it does what you need that would be great. So instead of having device,0,0-in you might have the person's name like "Jerry" so it would be Jerry-in and Jerry-out.

**Comment by iso-l588** [comment]
Hei Len!

On 16.06.2021 17:25, Len wrote:
> Studio-controls does already allow naming interfaces. Any added (extra) device can have that device's JACK client name set in the extra devices tab. This was added in version 2.1.60 beta (we are now up to 2.1.67 with bug fixes). However, I am not sure this is what you mean because you say "QjackCtrl makes this possible". Qjackctl actually allows renaming of _ports_ rather than the client itself and I have found that the port rename in Qjackctl does not show up in other applications always. The next release will be 2.2.0 which should be basically the same as 2.1.67 (I hope :)  )  So if you wish to try 2.1.67 and see if it does what you need that would be great. So instead of having device,0,0-in you might have the person's name like "Jerry" so it would be Jerry-in and Jerry-out.
> 

I guess I was not clear when speaking of QJackCtrl. What I meant was 
that you can open settings and name your presets as you wish. I always 
found that helpful since I often have the need to work with different 
interfaces. Since before Studio Controls I was never working with more 
than one device at a time, this had the same effect as naming the devices.

So naming devices as you're describing here sounds like just what I'm 
after. Seems like the need for QjackCtrl is rapidly vanishing...

I'll see in a few days if I can find time to test the 2.1.67, meanwhile 
keep up the good work!

Best regards,
Alf

**Comment by ovenwerks** [comment]
please try 2.1.68 rather than 2.1.67

**Comment by iso-l588** [comment]
I downloaded and installed and tried to run Studio Controls from the 
menu. Nothing.

 From terminal I get this:

$ studio-controls
install path: /usr/local

Config file: /home/alfh/.config/autojack/autojack.json
Traceback (most recent call last):
   File "/usr/local/bin/studio-controls", line 1831, in <module>
     us = StudioControls()
   File "/usr/local/bin/studio-controls", line 608, in __init__
     self.refresh_dropdowns()
   File "/usr/local/bin/studio-controls", line 867, in refresh_dropdowns
     if dev_db['firewire']:
KeyError: 'firewire'

My system is (K)Ubuntu Studio 20.04.

Best regards,
Alf
