### ISSUE TITLE
Studio Control hangs of Adding Bridges when Main Output is changed

### ISSUE THREAD

**Issue by jeanmartin13** [ovenwerks/studio-controls#77]
Hello,

I'm on ubuntustudio 21.10, using studio control with FFADO Firewire Modules (sound device MOTU 828 MKII). If I change the main output ports (default are system:playback_1 <firewire_pcm>), studio control statrts jack but hangs on "adding bridges". This is annoying because port audio connects to the main output ports, and on the FFADO implementation of my sound device system playback is phone outputs, not main outputs. So, for instance, if I playback a sound with Audacity I can't hear anything on the loud speakers which are connected to the main outputs of my device (FFADO jack ports 11 and 12).
It's surprising that one cannot change the studio control main output ports on another port than 1, seems to be a bug.
This doesn't happen if I start studio control with Main Output port set to system:playback_1 <firewire_pcm> (default "out of the box" setting; and then make the change to playback_11 (the main stereo output of the sound device I use), and then click on Apply Audio Settings. It happens if I start studio control with Main Output set to something different of system:playback_1 <firewire_pcm>

[log.zip](https://github.com/ovenwerks/studio-controls/files/8196604/log.zip)

**Comment by ovenwerks** [comment]
I see two things (maybe three):
1) You are running 2.2.8 and encountering a bug that has since been fixed. You should be able to get a more updated version by using ubuntustudio-installer to enable backports. The current version is 2.3.0.

2) Your phones setup will not work in anyway that makes sense. The whole Phones setup is made for two cases really. Auto sensing HDA phones being plugged in and a USB phones device plugged in with ports 1 and 2 as left and right. There is no method right now to set phones to some other port  numbers. This will be added down the road.  In any case phones will only work with an alsa device (system:playback* should be added I see). For your testing try changing phones to an HDA (PCH something) For sure you can not use you (unplugged) firewire device if you are using the firewire jack driver. I think I need to make it so any firewire device does not show up as an alsa device while the ffado drivers are in use.

3) You have your firewire device set up to be bridged? but the device is unplugged (used by ffado). While this should not cause any problems, it may. Again, I need to make that device disappear from all dialogs in ffado mode.

3) While I have a FW device it does not have dedicated phones or main out as yours does. You have selected system:playback_11/12 as your outputs which translate to pbk_Phones-L_out and pbk_Phones-R_out ok, but then it seems  they are listed as pbk_Main-L_out and pbk_Main-R_out. Does the name of ports 11/12 change if the phones are unplugged? or are the main ports different port numbers that debug doesn't show up?

Anyway, at least upgrade to version 2.3.0 and see how that goes.

**Comment by jeanmartin13** [comment]
Hello and thanks for the answer. I hope I understood well what you told me to do. I activated the backport and now version 2.3;0 is installed. But I still encounter the same issue. I join two log sets, one with control not hanging at add bridges steps, another with control hanging at add bridges.
Regarding the phone output. In fact I'm not using the phone output of my FW Motu device. The Motu has separate path for phones and main outputs. In fact it has something like 20 input/output.
I also join a screenshot of carla while studio control running well. Whrn hanging at adding bridges, the midi devices are even not appearing in carla's patchbay window.
I only noticed the issue lately because I started to use Audacity and this software use portaudio and portaudio connects to jack through the main outputs declared on Jack Master Settings tab of studio control. No matter what device I select on the extra device tab / Select device to edit, If I select something else than the default output ports in Jack Master setting, control hangs at startup on add bridges.
I have recognize that all those different configuration tabs, mainly the Extra Device one, are a bit confused to me (I don't see really what they are related to). And I didn't find a help page anywhere about studio control.

Edit :  I just noticed something, the mapping of the audioport of my FW device are not the same in studio-control than in qjackctl. I suppose those two apps are using the same FFADO driver ? Is there a reason why this mapping isn't the same ?

[log_hanging_add_bridges.zip](https://github.com/ovenwerks/studio-controls/files/8204889/log_hanging_add_bridges.zip)
[log_not_hanging_add_bridges.zip](https://github.com/ovenwerks/studio-controls/files/8204890/log_not_hanging_add_bridges.zip)
![jack_carla](https://user-images.githubusercontent.com/93234385/157215231-b6b25f18-53ad-489b-abd4-a8ac0d0f882d.png)

![qjackctl](https://user-images.githubusercontent.com/93234385/157243216-73bf8f35-27a8-4b3c-af74-2eaad67ebe63.png)

**Comment by ovenwerks** [comment]
The "mapping" of ports in Carla and Qjackctl are different from each other by Author's choice. In Carla the ports are listed in the order they are mapped in the device but in Qjackctl they are sorted alphabetically. The connections in both cases should still be connected to the same port names. Internally, we use device order for finding stereo pairs.

The hang bug above should be fixed in version 2.3.1
