### ISSUE TITLE
Two extra devices: device inputs become randomly crossed

### ISSUE THREAD

**Issue by Some-E** [ovenwerks/studio-controls#80]
Hi. I was using two M-Audio Delta 1010LT cards for ages, now Ubuntu Studio 20. The Studio Controls work fine with two cards, one main and one extra. Recently I got a third card of the same model, and naturally set up two extra cards. Issue: the inputs are no longer consistently in logical order in DAW (using Reaper native linux version, JACK). I don't know the details of how the inputs are enumerated, but it seems there is something wrong. Everything works, but the inputs are crossed, and not the same way after each boot. The picture makes it easier to understand. This is how Reaper may connect the inputs (after this particular boot):

![Carla 1010 x 3 Reaper wrong mapping](https://user-images.githubusercontent.com/57985244/166246287-692ec119-4056-46bb-a545-c29a277f2eef.png)

In Reaper the only related setting is the number of inputs. There is input mapping feature, but I'm not using it.
This may apply to the outputs as well, but I just haven't tried, only using the first 8 outputs in the system.

Solution attempt 1: I tried to solve it by manually wiring them correctly in Carla and saving it, but REAPER closes and reopens audio in a few cases during each session, so it requires constant attention and double clicking in Carla to load the setup when needed.

Solution attempt 2: I did a multi card setup on my own, and chose it as the only card in Studio Controls. This works, except that I didn't know how to enable MIDI (a2j and all). So I've proven all the cards work (also that they record and play correctly too), and the inputs can be setup in logical order.

**Comment by ovenwerks** [comment]
My first thought would be that this is a reaper bug/design choice. It appears that the bridge for M1010LT_2 starts adding ports before M1010LT_1 has finished adding it's ports. Reaper, rather than remembering which external ports to connect it's ports to, just connects them as they become available. As I say, a design choice.

In any case I have added a slight delay in version 2.3.4

a2jmidid should work the same if the devices are joined or not because the midi part is seen as a separate device.
