### ISSUE TITLE
Studio Controls 2.3.1 is registering duplicate USB devices

### ISSUE THREAD

**Issue by jamshark70** [ovenwerks/studio-controls#90]
Recently (this is a new symptom -- I'm not sure how long this has been going on), if I connect a previously-connected USB audio interface, but not the latest-connected USB, Studio Controls will add a new entry to its registry.

v2.3.1, I guess from Ubuntu Studio packages.

AFAICS the sequence goes something like this:

- Use USB interface A -- Studio Controls adds an entry for A. OK.
- Another day, in another room, use USB interface B. Studio Controls adds an entry for B. OK.
- Next day, use B. It matches the latest-used device and does not create new entry. OK.
- Back to the first room, use A again. Studio Controls keeps the old entry for A (and says it's "unplugged" -- wrong), *and* creates a new entry for A, which is plugged in.

This looks to me like it might be accidentally checking the device ID against only the last entry in the list, instead of searching the whole list...? Pure speculation on my part, but it fits my observation.

The fallout from this is two-fold:

1. The device list gets polluted. (There appears to be no way in the Studio Controls interface to clean up unwanted entries. At one point, I had manually edited autojack.json to remove all of them, and let Studio Controls rebuild the list. One time, that was successful. A second time, it caused Studio Controls to fail to open. So I don't think manual editing is a sustainable strategy.)

2. On a couple of occasions, I have seen JACK subsequently fail to connect to the USB device, leaving behind processes which cannot be killed, for which a total system reboot is the only apparent remedy. When this happens at the start of a class session or online meeting... not a good look.

Studio Controls has been working very well for me for the last year-plus. It's only in the last month or two that I've seen this bizarre behavior.

**Comment by jamshark70** [comment]
Just uploaded a gist of my autojack.json contents.

Duplicated devices:

- USB12 (https://gist.github.com/jamshark70/7e5ea212cccaf734e1390ff44dcb8fbd#file-gistfile1-txt-L167), USB17 (https://gist.github.com/jamshark70/7e5ea212cccaf734e1390ff44dcb8fbd#file-gistfile1-txt-L375)
- USB13 (https://gist.github.com/jamshark70/7e5ea212cccaf734e1390ff44dcb8fbd#file-gistfile1-txt-L203), USB16 (https://gist.github.com/jamshark70/7e5ea212cccaf734e1390ff44dcb8fbd#file-gistfile1-txt-L325)

I only just noticed that the duplicate entries' "bus" values differ. I'm not clear why this matters; in my past Ubuntu or Ubuntu Studio systems, the device would be configured by name in qjackctl, and I never needed to worry about which specific hardware bus it was attached to. And it didn't matter in the past on this system, either. Any ideas whether this is something in Studio Controls or something in the OS that changed?

**Comment by ovenwerks** [comment]
There are many USB devices that do not populate the serial number field 
for USB devices. In fact, I have only ever found one. Add to this, it is 
not uncommon for people to buy and use two or more USB mics of the same 
manufacture and model number or devicea that use generic chips. SO the 
only way to distinguish between two devices is to take the device 
imformation (two numbers manufacure ID, model ID) and the physical port 
the device is plugged into to allow differing settings for each device.

However, there has been problems here too. The ALSA information gives two 
numbers indicating bus/id but it turns out that these numbers are not the 
same from reboot to reboot or even from one plug event to the next as the 
ID changes while the bus may be the same for more than one physical port. 
None the less at one point in studio-controls development that was all the 
informaation we knew about and it seemed to work.

As we found that two devices could not always be recognized and that the 
same device could show up as a second number, I went searching for a 
better way of distinguishing devices or at least physical ports. This 
meant looking up the bus/ID that ALSA gave me in the USB device list and 
parsing for the physical port. By adding the physical port to the BUS 
value we could have information that stayed the same over reboots or plug 
events. However, old information in the database did not go away. Which 
leaves you with situation you have now.

Probably the best way to fix this is to manually remove the device from 
the .json file or to remove the file completely and start fresh.

I have stopped developing studio-controls about two years ago due to 
PipeWire becoming not only mainstream but in many distros, replacing pulse 
and jackd. Other life interests have also come into play as well as age.
In fact the jackd manitainer for both jackd1 and jackd2 has indicated that 
he considers PipeWire to be jackd3 and that is where he is putting his 
efforts. It is just now that PipeWire is becoming a reasonable choice for 
(semi)profesional audio work as it has reached v1.* and seems to check all 
the boxes. WHen or if I continue developing studio-controls, it will be 
based around pipewire.

I am sure this is not the best solution for your needs at this time but 
that is the way it is. I would suggest that if in the future another 
version of studio-controls becomes available that you do not install it as 
it will expect pipewire to be installed. In fact I may just start over 
with a new name and all to avoid that problem.

--
Len Ovens
www.ovenwerks.net

**Comment by jamshark70** [comment]
Thanks for the detailed explanation. Now I understand the difficulties (hadn't considered using multiple USB audio devices at once). And I also understand the lack of appeal of maintaining a tool that will soon be outdated (by pipewire).

I just reinstalled my old jack/pa scripts for qjackctl -- seems to be working, so I'll just manage audio devices the old way until my next OS upgrade.
